services:
  - type: web
    name: unisa-research-web
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn unisa_research.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unisa-db
          property: connectionString
      - key: REDIS_URL
        value: rediss://default:AYjnAAIjcDFhM2Q3N2VjODc4YjI0OWE4YmMwMzI2ZTA0OTg1OGU5MnAxMA@certain-lemur-35047.upstash.io:6379
      - key: CELERY_BROKER_URL
        value: ${{REDIS_URL}}/0
      - key: CELERY_RESULT_BACKEND
        value: ${{REDIS_URL}}/0

  - type: worker
    name: unisa-research-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A unisa_research worker --loglevel=info
    envVars:
      - key: REDIS_URL
        value: rediss://default:AYjnAAIjcDFhM2Q3N2VjODc4YjI0OWE4YmMwMzI2ZTA0OTg1OGU5MnAxMA@certain-lemur-35047.upstash.io:6379