# Generated by Django 5.2.1 on 2025-07-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publication_date', models.DateField()),
                ('keywords', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('scopus_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scholar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_url', models.URLField(max_length=255)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.publication')),
            ],
            options={
                'unique_together': {('author', 'publication', 'author_order')},
            },
        ),
    ]
