# Generated by Django 5.2.1 on 2025-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
