# Generated by Django 5.2.1 on 2025-08-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_publication_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.CharField(blank=True, choices=[('Scopus', 'Scopus'), ('Google Scholar', 'Google Scholar'), ('ORCID', 'ORCID')], max_length=50, null=True),
        ),
    ]
